### PR TITLE
Fixes #214

### PR DESCRIPTION
**Pull request by nikhilm**

### CODE REVIEW

**Comment by dpc** [comment]
Thank you!

**Comment by dpc** [comment]
Hmmm... makes me think ... should we cache it, so we don't have to call `atty` again and again?

**Comment by dpc** [comment]
Oh. This is already in a constructor. Nvmd.

**Comment by dpc** [comment]
If you want this deployed fast can you fill PR with updated CHANGELOG and minor version bump? I'd be able to publish on cargo.

**Comment by nikhilm** [comment]
Just to clarify, minor or patch version? This seems like a backward compatible bugfix.

**Comment by dpc** [comment]
Ah. Patch, yes.

**Pull request merged**
