### PR TITLE
Switch to atty

### PR DESCRIPTION
**Pull request by ignatenkobrain**
isatty is deprecated.

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by dpc** [comment]
This seem to bump our minium rust requirement. Can you figure out which version would that be exactly? If it is not too recent, I guess we could bump it.

**Comment by ignatenkobrain** [comment]
I think it is 1.18.0, I've bumped version in travis config.. Let's see.

**Comment by ignatenkobrain** [comment]
Nowadays everyone depends on 1.31+, so I don't think that this would be an issue

**Comment by ignatenkobrain** [comment]
lazy_static seems to require 1.24.1+, so I set that and now this is green.

**Comment by dpc** [comment]
One year old. I think it's going to be OK.

**Pull request merged**
